### ISSUE TITLE
Add logrotate.conf settings to deal with high volume of logs

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-profile_ldap_server#3]
Need to do something to handle crazy volume of log files that can fill disks rapidly.

e.g. add the following to `/etc/logrotate.conf` to match other LDAP servers:
```
# rotate log files weekly
weekly
maxsize 200M
```
...
```
# uncomment this if you want your log files compressed
compress
compresscmd /bin/bzip2
uncompresscmd /bin/bunzip2
compressoptions -9
compressext .bz2
```

**Comment by billglick** [comment]
We probably want to implement this via https://forge.puppet.com/modules/puppet/logrotate

The questions are:
1.  Should `puppet/logrotate` be part of all hosts with some sane defaults?
2. Can hiera for the ldap_server role override the configs specific for what we want there?

**Comment by billglick** [comment]
In theory, the following hiera parameters need to be set for the `ldap_server` role:
```yaml
::logrotate::config:
  compress: true
  compresscmd: "/bin/bzip2"
  compressoptions: "-9"
  compressext: ".bz2"
  maxsize: "200M"
  rotate_every: "weekly"
  uncompresscmd: "/bin/bunzip2"
```
